name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print goodbye
        run: echo "Bye"
      - name: print greetings
        run: echo "Hello world"
      
